name: GeoIPTools
main: uk.org.whoami.geoip.GeoIPTools
version: 'DEV'
authors:
- whoami
- Fishrock123
- Sindastra
dev-url: https://github.com/sindastra
commands:
    geoupdate:
        description: Update the GeoIPDatabase files
        usage: /geoupdate
        permission: geoiptools
permissions:
    geoiptools.*:
        description: Gives access to all GeoIPTools commands
        children:
            geoiptools.geoupdate: true
    geoiptools.geoupdate:
        description: Updates the database
        default: op
